
version: '3.3'

services:

   db:
     image: mysql:5.7
     restart: always
     volumes:
       #
       # Persist our MySQL data
       #
       - ./data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: wordpressrootpw
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   #
   # PHP FPM runs persistently, and services requests over port 9000
   # from our webserver.
   #
   php:
     depends_on:
       - db
     image: wordpress:5.0.0-fpm
     restart: always
     volumes:
       #
       # Copy in our PHP config for large uploads.
       #
       - ./php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
       #
       # When first run, this image populates /var/www/html/ with a Wordpress install,
       # and we want that to be exported so we have a copy of our code.
       #
       - ./wordpress:/var/www/html
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

   web:
     depends_on:
       - php
     image: nginx
     restart: always
     volumes:
       #
       # Import our Nginx configuration for FPM.
       #
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
       #
       # The webserver will also need to see our Wordpress install.
       #
       - ./wordpress:/var/www/html
       #
       # Write logs here.  Note that they will need to be 
       # rotated on the parent system.
       #
       - ./logs:/var/log/nginx
     ports:
       - 8080:80
     


